name: processing-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - tensorflow
    - keras
    - jupyter
    - notebook
